language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

services:
  - mongodb

before_script:
  - echo 'extension = "mongodb.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - ./scripts/travis
  - composer init --no-interaction --stability=dev
  - composer require "photon/session-mongodb:dev-master"
  - composer require "phpunit/phpunit:~5.0"
  - cp vendor/photon/session-mongodb/phpunit.xml .
  
script: ./vendor/bin/phpunit -c phpunit.xml

